import java.awt.*;
import java.awt.event.*;
import java.applet.*;
import javax.swing.*;
import javax.swing.border.*;
import java.net.URL;

public class Exercise17_9 extends JFrame {
  // Create image icons
  private ImageIcon icon1 = new ImageIcon("image/grapes.gif");

  private JPanel jpButtons = new JPanel();
  private JPanel jpSettings = new JPanel();
  private JPanel jpAlignment = new JPanel();
  private JButton jbt = new JButton();
  private TitledBorder titledBorder1;
  private TitledBorder titledBorder3;
  private GridLayout gridLayout3 = new GridLayout();
  private GridLayout gridLayout2 = new GridLayout();
  private JPanel jpHorizontalAlignment = new JPanel();
  private JPanel jpTextPosition = new JPanel();
  private BorderLayout borderLayout1 = new BorderLayout();
  private TitledBorder titledBorder2;
  private BorderLayout borderLayout2 = new BorderLayout();
  private JPanel jPanel1 = new JPanel();
  private JPanel jPanel2 = new JPanel();
  private BorderLayout borderLayout3 = new BorderLayout(15, 15);
  private JLabel jLabel1 = new JLabel();
  private JLabel jLabel2 = new JLabel();
  private GridLayout gridLayout1 = new GridLayout();
  private JComboBox jcboHoriAlignment = new JComboBox();
  private JComboBox jcboVertAlignment = new JComboBox();
  private GridLayout gridLayout5 = new GridLayout();
  private JPanel jPanel3 = new JPanel();
  private JPanel jPanel4 = new JPanel();
  private BorderLayout borderLayout4 = new BorderLayout(15, 15);
  private JLabel jLabel3 = new JLabel();
  private JLabel jLabel4 = new JLabel();
  private GridLayout gridLayout6 = new GridLayout();
  private JComboBox jcboHoriTextAlignment = new JComboBox();
  private JComboBox jcboVertTextAlignment = new JComboBox();
  private GridLayout gridLayout7 = new GridLayout();

  public Exercise17_9() {
    // Generated by JBuilder
    titledBorder1 = new TitledBorder("");
    titledBorder3 = new TitledBorder("");
    titledBorder2 = new TitledBorder("");
    this.setSize(new Dimension(400,300));
    setLayout(borderLayout1);
    jpButtons.setLayout(borderLayout2);
    jbt.setToolTipText("This is a JButton");
    jbt.setIcon(icon1);
    jbt.setText("Grapes");
    jpAlignment.setLayout(gridLayout3);
    titledBorder3.setTitle("Miscellanoues Options");
    jpHorizontalAlignment.setLayout(borderLayout3);
    jpHorizontalAlignment.setBorder(titledBorder1);
    jpTextPosition.setBorder(titledBorder2);
    jpTextPosition.setLayout(borderLayout4);
    titledBorder2.setTitle("Text Position Alignment");
    jLabel1.setText("Horizontal");
    jLabel2.setText("Vertical ");
    jPanel1.setLayout(gridLayout1);
    gridLayout1.setRows(2);
    jPanel2.setLayout(gridLayout5);
    gridLayout5.setRows(2);
    gridLayout5.setVgap(5);
    jLabel3.setText("Horizontal");
    jLabel4.setText("Vertical");
    jPanel3.setLayout(gridLayout6);
    gridLayout6.setRows(2);
    jPanel4.setLayout(gridLayout7);
    gridLayout7.setRows(2);
    gridLayout7.setVgap(5);
    jcboHoriAlignment.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        jcboHoriAlignment_actionPerformed(e);
      }
    });
    jcboVertAlignment.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        jcboVertAlignment_actionPerformed(e);
      }
    });
    jcboHoriTextAlignment.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        jcboHoriTextAlignment_actionPerformed(e);
      }
    });
    jcboVertTextAlignment.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(ActionEvent e) {
        jcboVertTextAlignment_actionPerformed(e);
      }
    });
    add(jpButtons, BorderLayout.CENTER);
    jpButtons.add(jbt, BorderLayout.CENTER);
    add(jpSettings, BorderLayout.SOUTH);
    jpSettings.setLayout(gridLayout2);
    jpSettings.add(jpAlignment, null);
    jpAlignment.add(jpHorizontalAlignment, null);
    jpHorizontalAlignment.add(jPanel1, BorderLayout.WEST);
    jPanel1.add(jLabel1, null);
    jPanel1.add(jLabel2, null);
    jpHorizontalAlignment.add(jPanel2, BorderLayout.CENTER);
    jPanel2.add(jcboHoriAlignment, null);
    jPanel2.add(jcboVertAlignment, null);
    jpAlignment.add(jpTextPosition, null);
    jpTextPosition.add(jPanel3, BorderLayout.WEST);
    jPanel3.add(jLabel3, null);
    jPanel3.add(jLabel4, null);
    jpTextPosition.add(jPanel4, BorderLayout.CENTER);
    jPanel4.add(jcboHoriTextAlignment, null);
    jPanel4.add(jcboVertTextAlignment, null);

    // Add items to the combo boxes
    jcboHoriAlignment.addItem("LEFT");
    jcboHoriAlignment.addItem("CENTER");
    jcboHoriAlignment.addItem("RIGHT");
    jcboVertAlignment.addItem("TOP");
    jcboVertAlignment.addItem("CENTER");
    jcboVertAlignment.addItem("BOTTOM");
    jcboHoriTextAlignment.addItem("LEFT");
    jcboHoriTextAlignment.addItem("CENTER");
    jcboHoriTextAlignment.addItem("RIGHT");
    jcboVertTextAlignment.addItem("TOP");
    jcboVertTextAlignment.addItem("CENTER");
    jcboVertTextAlignment.addItem("BOTTOM");

    jpAlignment.setBorder(new EmptyBorder(5, 5, 5, 5));
    jpHorizontalAlignment.setBorder(new CompoundBorder(
      new TitledBorder("Horizontal Alignment"), new EmptyBorder(5, 5, 5, 5)));
    jpTextPosition.setBorder(new CompoundBorder(
        new TitledBorder("Text Position"), new EmptyBorder(5, 5, 5, 5)));
  }

  // Main method
  public static void main(String[] args) {
    Exercise17_9 frame = new Exercise17_9();
    frame.setTitle("Exercise17_9");
    frame.setSize(400, 320);
    frame.setLocationRelativeTo(null); // Center the frame
    frame.setVisible(true);
  }

  void jcboHoriAlignment_actionPerformed(ActionEvent e) {
    String selectedItem = (String)jcboHoriAlignment.getSelectedItem();
    if (selectedItem.equals("LEFT"))
      jbt.setHorizontalAlignment(JButton.LEFT);
    if (selectedItem.equals("CENTER"))
      jbt.setHorizontalAlignment(JButton.CENTER);
    if (selectedItem.equals("RIGHT"))
      jbt.setHorizontalAlignment(JButton.RIGHT);
  }

  void jcboVertAlignment_actionPerformed(ActionEvent e) {
    String selectedItem = (String)jcboVertAlignment.getSelectedItem();
    if (selectedItem.equals("TOP"))
      jbt.setVerticalAlignment(JButton.TOP);
    if (selectedItem.equals("CENTER"))
      jbt.setVerticalAlignment(JButton.CENTER);
    if (selectedItem.equals("BOTTOM"))
      jbt.setVerticalAlignment(JButton.BOTTOM);
  }

  void jcboHoriTextAlignment_actionPerformed(ActionEvent e) {
    String selectedItem = (String)jcboHoriTextAlignment.getSelectedItem();
    if (selectedItem.equals("LEFT"))
      jbt.setHorizontalTextPosition(JButton.LEFT);
    if (selectedItem.equals("CENTER"))
      jbt.setHorizontalTextPosition(JButton.CENTER);
    if (selectedItem.equals("RIGHT"))
      jbt.setHorizontalTextPosition(JButton.RIGHT);
  }

  void jcboVertTextAlignment_actionPerformed(ActionEvent e) {
    String selectedItem = (String)jcboVertTextAlignment.getSelectedItem();
    if (selectedItem.equals("TOP"))
      jbt.setVerticalTextPosition(JButton.TOP);
    if (selectedItem.equals("CENTER"))
      jbt.setVerticalTextPosition(JButton.CENTER);
    if (selectedItem.equals("BOTTOM"))
      jbt.setVerticalTextPosition(JButton.BOTTOM);
  }
}

